# Github actions CI file
# Ryan Mulhall 2020
# CI testing for the FRE-NCtools repo, builds and runs unit tests
# github.com/noaa-gfdl/fre-nctools-container
name: FRE-NCtools CI
on: [push, pull_request]
jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        with_mpi: ['','--with-mpi']
        enable_quad_precision: ['', '--enable-quad-precision']
    container:
      image: noaagfdl/fre-nctools-base:2.0.0-focal
      env:
        MPI: ${{ matrix.with_mpi }}
        QUAD_P: ${{ matrix.enable_quad_precision }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Configure
      run: |
        python -m pip install --upgrade pip
        pip install xarray
        mkdir build && cd build
        autoreconf -i ../configure.ac
        ../configure $MPI $QUAD_P
    - name: Build tools
      run: make -C build
    - name: Run all tests
      if: matrix.with_mpi == ''
      run: make -C build -j check LOG_DRIVER_FLAGS=--comments
    - name: Run most tests (skip the slow ones)
      if: matrix.with_mpi == '--with-mpi'
      env:
        SKIP_TESTS: 4
      run: make -C build -j check LOG_DRIVER_FLAGS=--comments
    - name: Save log file on failure
      uses: actions/upload-artifact@v2.2.1
      if: failure()
      with:
        name: test-suite.log
        path: build/t/test-suite.log
